version: '3'
services:
  web:
    build:
      context: .
      target: final
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=assignment5;Username=hiphopgutt2;Password=hiphopgutt2;

  db:
    image: postgres
    environment:
      POSTGRES_DB: assignment5
      POSTGRES_USER: hiphopgutt2
      POSTGRES_PASSWORD: hiphopgutt2
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  proxy:
    image: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

  migration:
    build:
      context: .
      target: migration-env
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=assignment5;Username=hiphopgutt2;Password=hiphopgutt2;
    volumes:
      - .:/app
    entrypoint: ["dotnet", "ef"]
    #command: ["migrations", "update"]

volumes:
  db_data:
  caddy_data:
  caddy_config:
